apiVersion: v2
name: solr
description: "A helm chart to install Apache Solr: http://lucene.apache.org/solr/"
type: application
version: 1.0.0
appVersion: "1.16.0"
keywords:
  - "solr"
home: "http://lucene.apache.org/solr/"
sources:
  - "https://gitbox.apache.org/repos/asf?p=lucene-solr.git"
dependencies:
  - name: zookeeper
    version: "1.0.0"
    repository: "file://../zookeeper"
